baseurl = "http://naes.unr.edu/shoemaker/"
title = "Shoemaker Lab at UNR"
copyright = "&copy; 2016 Kevin T Shoemaker"
languageCode = "en-us"
theme = "academic"
image = "img/UNRlogo-1.jpg"

# Enable comments by entering your Disqus shortname
disqusShortname = "Lab_website"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
  name = "Kevin Shoemaker"
  role = "Assistant Professor, Wildlife Population Ecology"
  organization = "University of Nevada, Reno"
  avatar = "portrait.jpg"
  email = "kshoemaker@cabnr.unr.edu"
  address = "Natural Resources & Environmental Science, University of Nevada, Reno / mail stop 186, Reno, NV 89557, USA."
  phone = "(775)682-7449"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally
  #   on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and
  #   /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  #   Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = [
      "Population Viability Analysis",
      "Wildlife Conservation and Management",
      "Bayesian Statistics",
      "Machine Learning for Ecology" 

    ]
    str_interests = "Interests"
    str_education = "Education"

    [[params.about.education]]
      course = "PhD in Conservation Biology"
      institution = "SUNY ESF"
      year = 2011

    [[params.about.education]]
      course = "MS in Conservation Biology"
      institution = "SUNY ESF"
      year = 2007

    [[params.about.education]]
      course = "BSc in Biology"
      institution = "Haverford College"
      year = 2000

  # Selected Publications section.
  #   Section will only be displayed if there are publications with
  #   `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  #   Section will only be displayed if there are publications in
  #   `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  #   Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  #   Section will only be displayed if there are projects in
  #   `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:kevintshoemaker@gmail.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/KevinT_Kevin"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=BQtUdk8AAAAJ&hl=en"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/kevintshoemaker"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
