baseurl = ""
locale = "en-US"
title = "Shoemaker Lab"
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true

[pagination]
pagerSize = 20

[taxonomies]
tag = "tags"

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "People"
url = "/people/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 4

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 5

[[menu.main]]
name = "CV"
url = "/pdf/Shoemaker_CV_full.pdf"
weight = 6

[params]
description = "Applied Population Ecology Lab at UNR: practical applications of population ecology for wildlife management and conservation"
author = "Kevin Shoemaker"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
hideFooter = false
disableThemeToggle = false
ShowShareButtons = false
ShowReadingTime = false
disableSpecial1stPost = true
disableAnchoredHeadings = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowAllPagesInArchive = true
MainSections = ["people", "projects"]
ShowToc = false
disableScrollToTop = false
TocOpen = true
ShowWordCount = false
UseHugoToc = true
comments = false
math = false

[params.profileMode]
enabled = true
title = "Applied Population Ecology Lab at UNR"
subtitle = "The A.P.E. lab focuses on supporting the conservation and management of wildlife populations in the Great Basin and beyond using state-of-the-art analytical and simulation tools."
imageUrl = "/img/main/Massasauga2.jpg"
imageWidth = 160
imageHeight = 160

[[params.profileMode.buttons]]
name = "About"
url = "about/"

[[params.profileMode.buttons]]
name = "People"
url = "people/"

[[params.profileMode.buttons]]
name = "Projects"
url = "projects/"

[[params.profileMode.buttons]]
name = "Publications"
url = "publications/"

[[params.profileMode.buttons]]
name = "Teaching"
url = "teaching/"

[[params.profileMode.buttons]]
name = "CV"
url = "pdf/Shoemaker_CV_full.pdf"

[[params.socialIcons]]
name = "email"
url = "mailto:kevinshoemaker@unr.edu"

[[params.socialIcons]]
name = "github"
url = "https://github.com/kevintshoemaker"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kevin-shoemaker-10a561a"

[[params.socialIcons]]
name = "x"
url = "https://x.com/KevinT_Kevin"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/groups/1845083339044006/"

[params.assets]
disableScrollBarStyle = true

[params.cover]
hiddenInList = false
hiddenInSingle = true

[params.label]
text = "Shoemaker Lab"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
style = "autumn"

[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 2
