baseurl = "http://naes.unr.edu/shoemaker/lab/"
languageCode = "en-us"
title = "Applied Population Ecology Lab at UNR"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "lab-website"
googleAnalytics = "UA-84942309-1"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Applied Population Ecology Lab at UNR: practical applications of population ecology for wildlife management and conservation"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "A.P.E. Lab at UNR"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/shoemaker/lab/posts/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = false
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for APE lab Site
    customCSS            = ["/shoemaker/lab/css/main.min.css"]
    customJS             = ["/shoemaker/lab/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Applied Population Ecology Lab at UNR"

    paragraph = "The Applied Population Ecology lab at UNR focuses on supporting the conservation and management of wildlife populations in the Great Basin and beyond using state-of-the-art analytical and simulation tools"

    about     = "The current members of the A.P.E. lab are Kevin Shoemaker, Elizabeth Hunter, Margarete Walden, Miranda Crowell, and Danielle Miles. "

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/shoemaker/lab/img/main/Massasauga2.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    imperfect = false
    width     = ""
    alt       = "Hugo Future Imperfect"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 5

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Posts"
    url = "/categories/Posts/"    # correct syntax!!!
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    identifier = "fa fa-suitcase"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    identifier = "fa fa-camera"
    weight = 3

[[menu.main]]
    name = "People"
    url = "/categories/people/"
    identifier = "fa fa-users"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "/categories/projects/"
    identifier = "fa fa-folder"
    weight = 5

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "kevintshoemaker"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = "UCTogBbjLnTqnZJl5w_PgmVw"
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "kevin-shoemaker-10a561a"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "/groups/1845083339044006/"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "KevinT_Kevin"
    email           = ""
